Ajoute un cron quotidien pour exécuter le script de génération de stats MongoDB
betagouv/aides-jeunes-ops pull request #142
Opened 2023-07-05 14:14 UTC by Shamzic

[Tâche associée](https://trello.com/c/eJIZg4Pq/1361-cr%C3%A9er-une-t%C3%A2che-cron-quotidienne-pour-g%C3%A9n%C3%A9rer-les-fichiers-de-statistiques-mongo)

2023-07-06 13:54 UTC, baptou12 commented on roles/bootstrap/tasks/setup_cron.yaml
> +    name: Execute generate_mongo_stats.sh daily
J'ai un peu galéré mais quand on lance le playbook on fini avec seulement le cron pour la preprod et plus pour la prod (si on part d'un inventory avec d'abord prod puis preprod). Il semblerait qu'il faille rajouté `{{ item.name }}` dans le name du cron afin que ansible puisse différentier les deux : 
```suggestion
    name: Execute generate_mongo_stats.sh daily {{ item.name }}
```

2023-07-06 13:54 UTC, baptou12 requested changes
cf name du cron

2023-07-07 08:30 UTC, baptou12 approved these changes
LGTM juste une question en suspens sur la périodicité

2023-07-07 15:01 UTC, Shamzic commented
> LGTM juste une question en suspens sur la périodicité

Preneur d'un second avis de l'équipe dans ce cas 👍

2023-08-30 12:03 UTC, baptou12 commented
> La PR est ok pour moi ; il faut juste mettre à jour la commande utilisée pour lancer la génration des stats

+ le changement de la fréquence de every day à every month :-)

2023-09-03 17:53 UTC, merged