feat: ajoute un wrapper pour capturer les erreurs des crons sur sentry
betagouv/aides-jeunes-ops pull request #194
Opened 2024-08-14 16:53 UTC by Shamzic

2024-08-16 13:17 UTC, jenovateurs commented on roles/bootstrap/tasks/install_sentry_cli.yaml
> +- name: Install @sentry/cli using npm
Il va falloir lancer l'installation manuelle sur les deux serveurs en faisant un npm install sentry/cli.

2024-08-16 14:53 UTC, Shamzic commented on roles/bootstrap/tasks/install_sentry_cli.yaml
> +- name: Install @sentry/cli using npm
Je comprends pas trop ta remarque, ici cela s'installe en global. Pourquoi veux-tu faire un npm install en plus ?

2024-08-16 14:58 UTC, jenovateurs requested changes
Revue en mode lecture de code, je suis en cours de test avec Ansible.

2024-08-16 14:58 UTC, jenovateurs commented on roles/bootstrap/tasks/install_sentry_cli.yaml
> +- name: Install @sentry/cli using npm
Je me demandais si lorsqu'on va merge la PR si celle-ci va installer sentry ou non ? J'ai l'impression que c'est liée à Boostrap et que donc l'installation ne se fera pas automatiquement. Qu'en penses-tu ?

2024-08-16 16:37 UTC, Shamzic commented on roles/bootstrap/tasks/install_sentry_cli.yaml
> +- name: Install @sentry/cli using npm
Dès qu'on merge une pull request, la CD déclenche une connexion ssh vers le serveur associé à la branche cible et exécute le script update_ops.ssh ou update.ssh, dans les deux cas une réinstallation complète est effectuée avec le bootstrap

2024-08-16 16:46 UTC, Shamzic commented on roles/bootstrap/tasks/install_sentry_cli.yaml
> +    name: '@sentry/cli'
La version max de sentry/cli est la 2.33.1

2024-08-19 12:49 UTC, jenovateurs commented
Tester localement, les crontabs me semblent ok : 
<img width="1200" alt="Screenshot 2024-08-19 at 14 48 26" src="https://github.com/user-attachments/assets/26cf53d6-8776-4980-894a-d65f5caab008">

2024-08-23 10:12 UTC, jenovateurs commented
<img width="643" alt="Screenshot 2024-08-23 at 12 10 43" src="https://github.com/user-attachments/assets/fe719df1-a6ba-484e-826c-6b21618a72b1">

J'ai réussi à reproduire sans savoir comment après plusieurs tests. Je me demande s'il n'y aurait pas un soucis de droit à la lecture du fichier. env
On pourra s'en rendre compte en mettant en prod et en vérifiant que les scripts sont bien lancés.

2024-08-23 10:19 UTC, jenovateurs approved these changes
On peut commencer avec cette première itération tout en vérifiant après merge que tout fonctionne bien :-).

2024-08-28 08:42 UTC, merged

2024-08-28 09:07 UTC, Shamzic commented
J'ai mergé en préproduction, le déploiement est effectif sur eclipse mais les crontab ne sont pas à jour.. WIP

2024-08-28 09:52 UTC, Shamzic commented
Suggestion en lien proposée ici : https://github.com/betagouv/aides-jeunes-ops/pull/197